# Generated by Django 5.0.2 on 2025-07-23 14:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MirrorAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')],
                        default='processing',
                        max_length=20,
                    ),
                ),
                ('json_data', models.JSONField()),
                ('insights', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mirror_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
