# Generated by Django 5.0.2 on 2025-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_remove_json_data_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirroranalysis',
            name='person_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
