# Generated by Django 5.0.2 on 2025-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_mirroranalysis_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirroranalysis',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
