# Generated by Django 5.0.2 on 2025-08-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0004_alter_mirroranalysis_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirroranalysis',
            name='encrypted_analysis_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mirroranalysis',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
