# Generated by Django 5.0.2 on 2025-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0005_add_encryption_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirroranalysis',
            name='encrypted_analysis_data',
        ),
        migrations.RemoveField(
            model_name='mirroranalysis',
            name='encrypted_private_key',
        ),
        migrations.AddField(
            model_name='mirroranalysis',
            name='keypair',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
