# Generated by Django 5.0.2 on 2025-08-22 12:35

from django.db import migrations, models


def convert_insights_to_json_strings(apps, schema_editor):
    """Convert insights data to valid JSON strings before field type change"""
    MirrorAnalysis = apps.get_model('mirror', 'MirrorAnalysis')

    for analysis in MirrorAnalysis.objects.all():
        if analysis.insights and isinstance(analysis.insights, str):
            try:
                import json

                # Try to parse as JSON first
                parsed = json.loads(analysis.insights)
                # If it's already valid JSON, keep it as a string for now
                # The field type change will handle the conversion
            except (ValueError, TypeError):
                # If it's encrypted data, wrap it in a JSON structure as a string
                wrapped_data = {'encrypted_data': analysis.insights, 'data_type': 'encrypted', 'needs_decryption': True}
                analysis.insights = json.dumps(wrapped_data)
                analysis.save()


def reverse_convert_insights_to_json_strings(apps, schema_editor):
    """Reverse the conversion if needed"""
    MirrorAnalysis = apps.get_model('mirror', 'MirrorAnalysis')

    for analysis in MirrorAnalysis.objects.all():
        if analysis.insights and isinstance(analysis.insights, str):
            try:
                import json

                parsed = json.loads(analysis.insights)
                if isinstance(parsed, dict) and parsed.get('data_type') == 'encrypted':
                    # Extract the original encrypted data
                    analysis.insights = parsed.get('encrypted_data', '')
                    analysis.save()
            except (ValueError, TypeError):
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0006_remove_mirroranalysis_encrypted_analysis_data_and_more'),
    ]

    operations = [
        # First convert the data to valid JSON strings
        migrations.RunPython(
            convert_insights_to_json_strings,
            reverse_convert_insights_to_json_strings,
        ),
        # Then change the field type
        migrations.AlterField(
            model_name='mirroranalysis',
            name='insights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
