# Generated by Django 5.0.2 on 2025-09-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0007_alter_mirroranalysis_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirroranalysis',
            name='language',
            field=models.CharField(default='ru', help_text='Language for analysis output', max_length=10),
        ),
    ]
